### ISSUE TITLE
Bug: FAIL - Application already exists at path [/]

### ISSUE THREAD

**Issue by mgazzin** [sdkman/sdkman-cli#1168]
**Bug report**

When I try to deploy an application to tomcat, it fails

**To reproduce**

* install tomcat with $sdkman install tomcat
* install java with $sdk install java 17.0.5-oracle
* install netbeans
* compile the application
* deploy it

**System info**

SDKMAN 5.16.0

java: 17.0.5-oracle
tomcat: 10.0.22

I am getting the folloiwng error in Tomcat logs:

```

30-Jan-2023 13:40:44.410 SEVERE [Catalina-utility-1] org.apache.catalina.startup.ExpandWar.copy Error copying [/home/mgem/.sdkman/candidates/tomcat/10.0.22/temp/4-ROOT] to [/home/mgem/.sdkman/candidates/tomcat/10.0.22/temp/11-ROOT]
	java.io.FileNotFoundException: /home/mgem/.sdkman/candidates/tomcat/10.0.22/temp/4-ROOT (No such file or directory)
		at java.base/java.io.FileInputStream.open0(Native Method)
		at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
		at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
		at org.apache.catalina.startup.ExpandWar.copy(ExpandWar.java:269)
		at org.apache.catalina.startup.ContextConfig.antiLocking(ContextConfig.java:924)
		at org.apache.catalina.startup.ContextConfig.beforeStart(ContextConfig.java:965)
		at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:305)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:182)
		at org.apache.catalina.startup.HostConfig.reload(HostConfig.java:1542)
		at org.apache.catalina.startup.HostConfig.checkResources(HostConfig.java:1505)
		at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1744)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:316)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1162)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1365)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1369)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1347)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
		at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:833)
30-Jan-2023 13:40:44.411 SEVERE [Catalina-utility-1] org.apache.catalina.startup.HostConfig.reload Error during context [] restart
	org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.webresources.StandardRoot@3618bb7]
		at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
		at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4834)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4972)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.startup.HostConfig.reload(HostConfig.java:1542)
		at org.apache.catalina.startup.HostConfig.checkResources(HostConfig.java:1505)
		at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1744)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:316)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1162)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1365)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1369)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1347)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
		at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:833)
	Caused by: java.lang.IllegalArgumentException: The main resource set specified [/home/mgem/.sdkman/candidates/tomcat/10.0.22/temp/4-ROOT] is not valid
		at org.apache.catalina.webresources.StandardRoot.createMainResourceSet(StandardRoot.java:762)
		at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:719)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		... 19 more
30-Jan-2023 13:40:54.413 INFO [Catalina-utility-2] org.apache.catalina.startup.HostConfig.reload Reloading context []
30-Jan-2023 13:40:54.413 INFO [Catalina-utility-2] org.apache.catalina.util.LifecycleBase.stop The stop() method was called on component [WebappLoader[StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]] after stop() had already been called. The second call will be ignored.
30-Jan-2023 13:40:54.413 INFO [Catalina-utility-2] org.apache.catalina.util.LifecycleBase.destroy The destroy() method was called on component [org.apache.catalina.webresources.DirResourceSet@609eadd9] after destroy() had already been called. The second call will be ignored.
30-Jan-2023 13:40:54.415 SEVERE [Catalina-utility-2] org.apache.catalina.startup.ExpandWar.copy Error copying [/home/mgem/.sdkman/candidates/tomcat/10.0.22/temp/4-ROOT] to [/home/mgem/.sdkman/candidates/tomcat/10.0.22/temp/12-ROOT]
	java.io.FileNotFoundException: /home/mgem/.sdkman/candidates/tomcat/10.0.22/temp/4-ROOT (No such file or directory)
		at java.base/java.io.FileInputStream.open0(Native Method)
		at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
		at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
		at org.apache.catalina.startup.ExpandWar.copy(ExpandWar.java:269)
		at org.apache.catalina.startup.ContextConfig.antiLocking(ContextConfig.java:924)
		at org.apache.catalina.startup.ContextConfig.beforeStart(ContextConfig.java:965)
		at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:305)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:182)
		at org.apache.catalina.startup.HostConfig.reload(HostConfig.java:1542)
		at org.apache.catalina.startup.HostConfig.checkResources(HostConfig.java:1505)
		at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1744)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:316)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1162)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1365)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1369)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1347)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
		at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:833)
30-Jan-2023 13:40:54.416 SEVERE [Catalina-utility-2] org.apache.catalina.startup.HostConfig.reload Error during context [] restart
	org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.webresources.StandardRoot@3618bb7]
		at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
		at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4834)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4972)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.startup.HostConfig.reload(HostConfig.java:1542)
		at org.apache.catalina.startup.HostConfig.checkResources(HostConfig.java:1505)
		at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1744)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:316)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1162)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1365)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1369)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1347)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
		at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:833)
	Caused by: java.lang.IllegalArgumentException: The main resource set specified [/home/mgem/.sdkman/candidates/tomcat/10.0.22/temp/4-ROOT] is not valid
		at org.apache.catalina.webresources.StandardRoot.createMainResourceSet(StandardRoot.java:762)
		at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:719)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		... 19 more

```

I have tried to apply:

```$chmod -R 777 tomcat```

to tomcat directory but nothing changes.
Anyone is getting the same issue?

**Comment by marc0der** [comment]
This looks like an application deployment issue, not a Tomcat installation problem. The Java process is running so Tomcat is installed and working.

Please follow the contributing guidelines before opening a bug report here.
